language: node_js
node_js:
  - "stable" #version of node js
cache:
  directories:
    - node_modules
script:
  - npm install
  - unset CI #To avoid build failure due to warnings
  - npm run build
before_deploy: "echo 'Deployment in progress on $TRAVIS_BRANCH...'"
deploy:
  if: branch = dev
  provider: s3
  skip_cleanup: true #Skip cleaning up the build folder before deploy/upload
  access_key_id: "AKIAIQPGI6TTKCITNVVA"
  secret_access_key: 
    secure: "Rug6OasQDa/+nCGTgTcmktSE3XQYm1m7hx1Y4T5gozOqbXqtRdC2WySKYJboPw420RdhnDaIh5ctjLcKXGfvDIWhFiMnAsGS5ptwLfP/wJae0JgANq+DbXxXjEMctD1T/uWBpDJKiI1HdnjLRIygrX7L8nvWMzmdPMIn1b5xQ8whG76U/rKxtzrATbeNjYyQ/623LEHr4U0umQT2dN7d4YTaDPlJ5gQgQR5WX29CD9xIHC+X/p55wYn/p605tft8Y246acLoAFYK1KmcWOAJLxMlmV6Sq0Pv3QEsyOYTVtiHpLdfveYjxQORQihny4K3zlX5zBoNVbGasSFjNyhUW2NHucFJ6NrclC8YEms+0LCj8jYoR0sWjUuSSv2gyg9C2Nhv8iVhILN8GdZmG8CaTv6y2iPY0dbEsOPtb3k+tEqIYD5+fi8+mz920rUQ4CsgdyZoPLPoc968zT0WjnRKvGJNx96qMTXOFwodOQ/prepOHKg6gBbmTPLVYggJowj/coBGTThbxVpQ3/nJho9eNOk0LUc5B07iLigiWlI+DZVqMl+zQG81lylo+ldDSuwgXrmgamgoHFDxuytjxTOh8gowvrz8wd/WBcNpOpWP43YWwi04rIua7RDfVoKHEGGPjVx9hXkTTZwoY/QBjYxxX97Y9sE1qAEJpkmtLLMTGpM="
  bucket: "winwin-frontend-bucket"
  local_dir: build #Upload only this directory
  region: "us-east-2"
  on:
    branch: dev

deploy:
  if: branch = master
  provider: s3
  skip_cleanup: true #Skip cleaning up the build folder before deploy/upload
  access_key_id: "AKIAIQPGI6TTKCITNVVA"
  secret_access_key: 
    secure: "Rug6OasQDa/+nCGTgTcmktSE3XQYm1m7hx1Y4T5gozOqbXqtRdC2WySKYJboPw420RdhnDaIh5ctjLcKXGfvDIWhFiMnAsGS5ptwLfP/wJae0JgANq+DbXxXjEMctD1T/uWBpDJKiI1HdnjLRIygrX7L8nvWMzmdPMIn1b5xQ8whG76U/rKxtzrATbeNjYyQ/623LEHr4U0umQT2dN7d4YTaDPlJ5gQgQR5WX29CD9xIHC+X/p55wYn/p605tft8Y246acLoAFYK1KmcWOAJLxMlmV6Sq0Pv3QEsyOYTVtiHpLdfveYjxQORQihny4K3zlX5zBoNVbGasSFjNyhUW2NHucFJ6NrclC8YEms+0LCj8jYoR0sWjUuSSv2gyg9C2Nhv8iVhILN8GdZmG8CaTv6y2iPY0dbEsOPtb3k+tEqIYD5+fi8+mz920rUQ4CsgdyZoPLPoc968zT0WjnRKvGJNx96qMTXOFwodOQ/prepOHKg6gBbmTPLVYggJowj/coBGTThbxVpQ3/nJho9eNOk0LUc5B07iLigiWlI+DZVqMl+zQG81lylo+ldDSuwgXrmgamgoHFDxuytjxTOh8gowvrz8wd/WBcNpOpWP43YWwi04rIua7RDfVoKHEGGPjVx9hXkTTZwoY/QBjYxxX97Y9sE1qAEJpkmtLLMTGpM="
  bucket: "winwin-frontend-bucket-prod"
  local_dir: build #Upload only this directory
  region: "us-east-2"
  on:
    branch: master
after_deploy: 
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
"echo 'Deployment is complete on $TRAVIS_BRANCH.'"