language: node_js
node_js:
  - "11" #version of node js
cache:
  directories:
    - node_modules
script:
  - echo "Starting build on $TRAVIS_BRANCH branch"
  - npm install
  - unset CI #To avoid build failure due to warnings
  - npm run build
before_deploy: 
  - echo "Deployment in progress"

-: &s3_deploy
    provider: s3
    access_key_id: "AKIAIQPGI6TTKCITNVVA"
    secret_access_key: 
      secure: "Rug6OasQDa/+nCGTgTcmktSE3XQYm1m7hx1Y4T5gozOqbXqtRdC2WySKYJboPw420RdhnDaIh5ctjLcKXGfvDIWhFiMnAsGS5ptwLfP/wJae0JgANq+DbXxXjEMctD1T/uWBpDJKiI1HdnjLRIygrX7L8nvWMzmdPMIn1b5xQ8whG76U/rKxtzrATbeNjYyQ/623LEHr4U0umQT2dN7d4YTaDPlJ5gQgQR5WX29CD9xIHC+X/p55wYn/p605tft8Y246acLoAFYK1KmcWOAJLxMlmV6Sq0Pv3QEsyOYTVtiHpLdfveYjxQORQihny4K3zlX5zBoNVbGasSFjNyhUW2NHucFJ6NrclC8YEms+0LCj8jYoR0sWjUuSSv2gyg9C2Nhv8iVhILN8GdZmG8CaTv6y2iPY0dbEsOPtb3k+tEqIYD5+fi8+mz920rUQ4CsgdyZoPLPoc968zT0WjnRKvGJNx96qMTXOFwodOQ/prepOHKg6gBbmTPLVYggJowj/coBGTThbxVpQ3/nJho9eNOk0LUc5B07iLigiWlI+DZVqMl+zQG81lylo+ldDSuwgXrmgamgoHFDxuytjxTOh8gowvrz8wd/WBcNpOpWP43YWwi04rIua7RDfVoKHEGGPjVx9hXkTTZwoY/QBjYxxX97Y9sE1qAEJpkmtLLMTGpM="
    local_dir: build #Upload only this directory
    skip_cleanup: true #Skip cleaning up the build folder before deploy/upload
    region: "us-east-2"
    wait-until-deployed: true

deploy:
  # make dev build and deploy in dev bucket
  - <<: *s3_deploy
    on:
      branch: dev
    bucket: "winwin-frontend-bucket"
  
  # make prod build and deploy in prod bucket
  - <<: *s3_deploy
    on:
      branch: master
    bucket: "winwin-frontend-bucket-prod"
after_deploy: 
  - echo "Deployment is complete"
  #The below command creates a invalidation on cloud front which clears all the caches on server to reflect fresh changes
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST

notifications:
  slack:
    secure: jX7hpOv7QeNbVPnOnfEt75VJPIRO3QuBvBuZIzZyKHtIXPbEN6cBql6xT7DbTV5vdAklrOjJd58cxfGqz1O7OooLDqAH10YFqSicQwavg+VkjCuwqMqLJsCXhOVQq/p70B9ZQcw6JmFyt0IVF6fGWo86subzFA8KE/8UJXDmJARyzfhD1fY/bCYwSkjBl6r7FnUoFN6ipUbvOC2E1v7+i1j6IUtPwv1v2ghfBgxOQC2vziU8Q4i3uX98Zn40eRc/5kOse3FOXtI94a0+ElVNg9nuABHTYm6yAEOHKOdGW5UY3MbpLVoROFWYVZNclWdIzka/mSEtodiEU6pntSYUMZ9KP3H0xST+OhSBmFkQo7Qi3Wr769ylQfo7C8QW8AsdOxrLO7KR/TDsxFh0AfIAtVZHW1HipmeMjCMneV+C3BjTl79UW/4/zXB4CqL8ygPDcfRtHSSP6q6PZ/QdlOtEx9JdMetxUJxP0X1p7q0E5Ov9p+g6hE1UzEf47olK/+Lwm6I7FxfSOskT3+dyx6XTuJnflP6P6sZwZHx6Yl4DO1nWJ328ddhfCaH9tbhdq1J4thsKmpOUBW+s2Wnmvq52n1Nl9LIMXWGRD/LRgkBIPyTX09VZpe8TpXM8cZSalRnH0cJ5BHlgFalOpjARv42PjrAE/fpIvMcMHRT8SKGum4s=