language: node_js
node_js:
  - "stable" #version of node js
cache:
  directories:
    - node_modules
script:
  - npm install
  - unset CI
  - npm run build
before_deploy: "echo 'Deploying to dev...'"
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: "AKIAJ6VN6S2NGB6JQEFA"
  secret_access_key: "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"
  bucket: "winwin-frontend-bucket"
  project: ./build/
  region: "us-east-2"
  on:
    #all_branches: true
    branch: dev
after_deploy: "echo 'Deployment to dev is complete.'"