--- 
? "-"
: 
  access_key_id: $AWS_ACCESS_KEY_ID
  local_dir: build
  provider: s3
  region: us-east-2
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  wait-until-deployed: true
after_deploy: 
  - "echo \"Deployment is complete\""
  - "aws configure set preview.cloudfront true"
  - "if [ \"$TRAVIS_BRANCH\" = \"dev\"]; then - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID_DEV --paths \"/*\" fi;"
  - "if [ \"$TRAVIS_BRANCH\" = \"staging\"]; then - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID_STAG --paths \"/*\" fi;"
  - "if [ \"$TRAVIS_BRANCH\" = \"master\"]; then - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID_PROD --paths \"/*\" fi;"
before_deploy: 
  - "echo \"Deployment in progress\""
before_install: 
  - "pip install --user awscli"
cache: 
  directories: 
    - node_modules
deploy: 
  - 
    access_key_id: $AWS_ACCESS_KEY_ID
    bucket: winwin-frontend-bucket
    local_dir: build
    provider: s3
    region: us-east-2
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    true: 
      branch: dev
    wait-until-deployed: true
  - 
    access_key_id: $AWS_ACCESS_KEY_ID
    bucket: winwin-frontend-bucket-stag
    local_dir: build
    provider: s3
    region: us-west-2
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    true: 
      branch: staging
    wait-until-deployed: true
  - 
    access_key_id: $AWS_ACCESS_KEY_ID
    bucket: winwin-frontend-bucket-prod
    local_dir: build
    provider: s3
    region: us-west-2
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    true: 
      branch: master
    wait-until-deployed: true
install: true
language: node_js
node_js: 
  - "11"
notifications: 
  slack: 
    secure: jX7hpOv7QeNbVPnOnfEt75VJPIRO3QuBvBuZIzZyKHtIXPbEN6cBql6xT7DbTV5vdAklrOjJd58cxfGqz1O7OooLDqAH10YFqSicQwavg+VkjCuwqMqLJsCXhOVQq/p70B9ZQcw6JmFyt0IVF6fGWo86subzFA8KE/8UJXDmJARyzfhD1fY/bCYwSkjBl6r7FnUoFN6ipUbvOC2E1v7+i1j6IUtPwv1v2ghfBgxOQC2vziU8Q4i3uX98Zn40eRc/5kOse3FOXtI94a0+ElVNg9nuABHTYm6yAEOHKOdGW5UY3MbpLVoROFWYVZNclWdIzka/mSEtodiEU6pntSYUMZ9KP3H0xST+OhSBmFkQo7Qi3Wr769ylQfo7C8QW8AsdOxrLO7KR/TDsxFh0AfIAtVZHW1HipmeMjCMneV+C3BjTl79UW/4/zXB4CqL8ygPDcfRtHSSP6q6PZ/QdlOtEx9JdMetxUJxP0X1p7q0E5Ov9p+g6hE1UzEf47olK/+Lwm6I7FxfSOskT3+dyx6XTuJnflP6P6sZwZHx6Yl4DO1nWJ328ddhfCaH9tbhdq1J4thsKmpOUBW+s2Wnmvq52n1Nl9LIMXWGRD/LRgkBIPyTX09VZpe8TpXM8cZSalRnH0cJ5BHlgFalOpjARv42PjrAE/fpIvMcMHRT8SKGum4s=
script: 
  - "echo \"Starting build on $TRAVIS_BRANCH branch\""
  - "npm install"
  - "unset CI"
  - "npm run build"
