export const SET_LOGIN_PENDING = 'auth/SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'auth/SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'auth/SET_LOGIN_ERROR';
export const SET_FORM_ERROR = 'auth/SET_FORM_ERROR';
//reset password
export const SET_RESETPASSWORD_PENDING = 'auth/SET_RESETPASSWORD_PENDING';
export const SET_RESETPASSWORD_SUCCESS = 'auth/SET_RESETPASSWORD_SUCCESS';
export const SET_RESETPASSWORD_ERROR = 'auth/SET_RESETPASSWORD_ERROR';
export const SET_RESETFORM_ERROR = 'auth/SET_RESETFORM_ERROR';
//forget password
export const SET_FP_PENDING = 'auth/SET_FP_PENDING';
export const SET_FP_SUCCESS = 'auth/SET_FFP_SUCCESS';
export const SET_FP_ERROR = 'auth/SET_FP_ERROR';
export const SET_FPFORM_ERROR = 'auth/SET_FPFORM_ERROR';
//create org
export const SET_CREATEORG_PENDING = 'org/SET_CREATEORG_PENDING';
export const SET_CREATEORG_SUCCESS = 'org/SET_CREATEORG_SUCCESS';
export const SET_CREATEORG_ERROR = 'org/SET_CREATEORG_ERROR';
export const SET_CREATEORGFORM_ERROR = 'org/SET_CREATEORGFORM_ERROR';
//org landing
export const SET_FETCHORG_PENDING = 'org/SET_FETCHORG_PENDING';
export const SET_FETCHORG_SUCCESS = 'org/SET_FETCHORG_SUCCESS';
export const SET_FECTHORG_ERROR = 'org/SET_FECTHORG_ERROR';
export const FILTER_ORG_LIST = 'org/FILTER_ORG_LIST';
//filter org
export const SET_APPLIED_FILTER = 'org/SET_APPLIED_FILTER';
export const SET_APPLIED_FILTER_FLAG = 'org/SET_APPLIED_FILTER_FLAG';
export const SET_FILTERED_LIST_ERROR = 'org/SET_FILTERED_LIST_ERROR';
export const SET_FILTERED_LIST_PENDING = 'org/SET_FILTERED_LIST_PENDING';
export const SET_FILTERED_LIST_SUCCESS = 'org/SET_FILTERED_LIST_SUCCESS';
//spi tags
export const FETCH_SPITAGS_PENDING = 'org/FETCH_SPITAGS_PENDING';
export const FETCH_SPITAGS_SUCCESS = 'org/FETCH_SPITAGS_SUCCESS';
export const FETCH_SPITAGS_ERROR = 'org/FETCH_SPITAGS_ERROR';
//sdg tags
export const FETCH_SDGTAGS_PENDING = 'org/FETCH_SDGTAGS_PENDING';
export const FETCH_SDGTAGS_SUCCESS = 'org/FETCH_SDGTAGS_SUCCESS';
export const FETCH_SDGTAGS_ERROR = 'org/FETCH_SDGTAGS_ERROR';
//regions served
export const FETCH_REGIONSERVED_PENDING = 'org/FETCH_REGIONSERVED_PENDING';
export const FETCH_REGIONSERVED_SUCCESS = 'org/FETCH_REGIONSERVED_SUCCESS';
export const FETCH_REGIONSERVED_ERROR = 'org/FETCH_REGIONSERVED_ERROR';
export const SET_REGIONSERVED_PENDING = 'org/SET_REGIONSERVED_PENDING';
export const SET_REGIONSERVED_SUCCESS = 'org/SET_REGIONSERVED_SUCCESS';
export const SET_REGIONSERVED_ERROR = 'org/SET_REGIONSERVED_ERROR';
//org detail
export const SET_FETCHORGDETAIL_PENDING = 'org/SET_FETCHORGDETAIL_PENDING';
export const SET_FETCHORGDETAIL_SUCCESS = 'org/SET_FETCHORGDETAIL_SUCCESS';
export const SET_FECTHORGDETAIL_ERROR = 'org/SET_FECTHORGDETAIL_ERROR';
//program list
export const SET_FETCHPROGRAM_PENDING = 'program/SET_FETCHPROGRAM_PENDING';
export const SET_FETCHPROGRAM_SUCCESS = 'program/SET_FETCHPROGRAM_SUCCESS';
export const SET_FECTHPROGRAM_ERROR = 'program/SET_FECTHPROGRAM_ERROR';

