//loading
export const LOADER_START = 'loader/LOADER_START';
export const LOADER_STOP = 'loader/LOADER_STOP';
//login
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'auth/LOGIN_ERROR';
export const SET_FORM_ERROR = 'auth/SET_FORM_ERROR';
export const LOAD_USER_FROM_STORAGE = 'auth/LOAD_USER_FROM_STORAGE';
export const LOGOUT = 'auth/LOGOUT'
//reset password
export const RESETPASSWORD_REQUEST = 'auth/RESETPASSWORD_REQUEST';
export const RESETPASSWORD_SUCCESS = 'auth/RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_ERROR = 'auth/RESETPASSWORD_ERROR';
//forget password
export const FP_REQUEST = 'auth/FP_REQUEST';
export const FP_SUCCESS = 'auth/FP_SUCCESS';
export const FP_ERROR = 'auth/FP_ERROR';
//users
export const USERINFO_REQUEST = 'user/USERINFO_REQUEST';
export const USERINFO_SUCCESS = 'user/USERINFO_SUCCESS';
export const USERINFO_ERROR = 'user/USERINFO_ERROR';
//create org
export const SET_CREATEORG_PENDING = 'org/SET_CREATEORG_PENDING';
export const SET_CREATEORG_SUCCESS = 'org/SET_CREATEORG_SUCCESS';
export const SET_CREATEORG_ERROR = 'org/SET_CREATEORG_ERROR';
export const SET_CREATEORGFORM_ERROR = 'org/SET_CREATEORGFORM_ERROR';
//org landing
export const FETCHORG_REQUEST = 'org/FETCHORG_REQUEST';
export const FETCHORG_SUCCESS = 'org/FETCHORG_SUCCESS';
export const FECTHORG_ERROR = 'org/FECTHORG_ERROR';
export const FILTER_ORG_LIST = 'org/FILTER_ORG_LIST';
export const SET_SDGLIST = 'org/SET_SDGLIST';
export const SET_SPILIST = 'org/SET_SPILIST';
export const SET_APPLIED_FILTER = 'org/SET_APPLIED_FILTER';
//filter org
export const SET_FILTERED_LIST_ERROR = 'org/SET_FILTERED_LIST_ERROR';
export const SET_FILTERED_LIST_PENDING = 'org/SET_FILTERED_LIST_PENDING';
export const SET_FILTERED_LIST_SUCCESS = 'org/SET_FILTERED_LIST_SUCCESS';
//spi tags
export const FETCH_SPITAGS_PENDING = 'org/FETCH_SPITAGS_PENDING';
export const FETCH_SPITAGS_SUCCESS = 'org/FETCH_SPITAGS_SUCCESS';
export const FETCH_SPITAGS_ERROR = 'org/FETCH_SPITAGS_ERROR';
//sdg tags
export const FETCH_SDGTAGS_PENDING = 'org/FETCH_SDGTAGS_PENDING';
export const FETCH_SDGTAGS_SUCCESS = 'org/FETCH_SDGTAGS_SUCCESS';
export const FETCH_SDGTAGS_ERROR = 'org/FETCH_SDGTAGS_ERROR';
//regions served
export const FETCH_REGIONSERVED_PENDING = 'org/FETCH_REGIONSERVED_PENDING';
export const FETCH_REGIONSERVED_SUCCESS = 'org/FETCH_REGIONSERVED_SUCCESS';
export const FETCH_REGIONSERVED_ERROR = 'org/FETCH_REGIONSERVED_ERROR';
export const SET_REGIONSERVED_PENDING = 'org/SET_REGIONSERVED_PENDING';
export const SET_REGIONSERVED_SUCCESS = 'org/SET_REGIONSERVED_SUCCESS';
export const SET_REGIONSERVED_ERROR = 'org/SET_REGIONSERVED_ERROR';
//org detail
export const SET_FETCHORGDETAIL_PENDING = 'org/SET_FETCHORGDETAIL_PENDING';
export const SET_FETCHORGDETAIL_SUCCESS = 'org/SET_FETCHORGDETAIL_SUCCESS';
export const SET_FECTHORGDETAIL_ERROR = 'org/SET_FECTHORGDETAIL_ERROR';

//prog detail
export const SET_FETCHPROGDETAIL_PENDING = 'org/SET_FETCHPROGDETAIL_PENDING';
export const SET_FETCHPROGDETAIL_SUCCESS = 'org/SET_FETCHPROGDETAIL_SUCCESS';
export const SET_FECTHPROGDETAIL_ERROR = 'org/SET_FECTHPROGDETAIL_ERROR';

//program list
export const SET_FETCHPROGRAM_PENDING = 'program/SET_FETCHPROGRAM_PENDING';
export const SET_FETCHPROGRAM_SUCCESS = 'program/SET_FETCHPROGRAM_SUCCESS';
export const SET_FECTHPROGRAM_ERROR = 'program/SET_FECTHPROGRAM_ERROR';

//resources
export const FETCH_RESOURCES_PENDING = 'org/FETCH_RESOURCES_PENDING';
export const FETCH_RESOURCES_SUCCESS = 'org/FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_ERROR = 'org/FETCH_RESOURCES_ERROR';
export const SET_RESOURCES_PENDING = 'org/SET_RESOURCES_PENDING';
export const SET_RESOURCES_SUCCESS = 'org/SET_RESOURCES_SUCCESS';
export const SET_RESOURCES_ERROR = 'org/SET_RESOURCES_ERROR';

// data sets
export const FETCH_DATASET_PENDING = 'org/FETCH_RESOURCES_PENDING';
export const FETCH_DATASET_SUCCESS = 'org/FETCH_RESOURCES_SUCCESS';
export const FETCH_DATASET_ERROR = 'org/FETCH_DATASET_ERROR';
export const SET_DATASET_PENDING = 'org/SET_DATASET_PENDING';
export const SET_DATASET_SUCCESS = 'org/SET_DATASET_SUCCESS';
export const SET_DATASET_ERROR = 'org/SET_DATASET_ERROR';

//section header
export const ADD_APP_NAVIGATION = 'header/ADD_APP_NAVIGATION';
export const REMOVE_APP_NAVIGATION = 'header/REMOVE_APP_NAVIGATION';

//Data Feed
export const SET_DATAFEED_PENDING = 'org/SET_DATAFEED_PENDING';
export const SET_DATAFEED_SUCCESS = 'org/SET_DATAFEED_SUCCESS';
export const SET_DATAFEED_ERROR = 'org/SET_DATAFEED_ERROR';
export const SET_DATAFEEDFORM_ERROR = 'org/SET_DATAFEEDFORM_ERROR';

//Org History
export const SET_FETCHORGHISTORY_PENDING = 'org/SET_FETCHORGHISTORY_PENDING';
export const SET_FETCHORGHISTORY_SUCCESS = 'org/SET_FETCHORGHISTORY_SUCCESS';
export const SET_FECTHORGHISTORY_ERROR = 'org/SET_FECTHORGHISTORY_ERROR';

//Org Hierarchy
export const SET_FETCHORGHEIRARCHY_PENDING = 'org/SET_FETCHORGHEIRARCHY_PENDING';
export const SET_FETCHORGHEIRARCHY_SUCCESS = 'org/SET_FETCHORGHEIRARCHY_SUCCESS';
export const SET_FECTHORGHEIRARCHY_ERROR = 'org/SET_FECTHORGHEIRARCHY_ERROR';

//User Management List
export const SET_FETCHUSER_PENDING = 'userManagmenet/SET_FETCHUSER_PENDING';
export const SET_FETCHUSER_SUCCESS = 'userManagmenet/SET_FETCHUSER_SUCCESS';
export const SET_FETCHUSER_ERROR = 'userManagmenet/SET_FETCHUSER_ERROR';

//Notes
export const FETCH_NOTES_PENDING = 'org/FETCH_NOTES_PENDING';
export const FETCH_NOTES_SUCCESS = 'org/FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_ERROR = 'org/FETCH_NOTES_ERROR';
